- block:

  - name: homebrew update
    homebrew:
      update_homebrew: no
      upgrade_all: no

  - name: homebrew tap
    homebrew_tap:
      name: '{{ item }}'
      state: present
    with_items: '{{ taps }}'

  - name: homebrew packages install
    homebrew:
      name: '{{ item.name }}'
      state: "{{ item.state | default('present') }}"
    with_items: '{{ packages }}'

  tags:
    - homebrew

